### ISSUE TITLE
Maiar extension error

### ISSUE THREAD

**Issue by bogdanIuga** [elrond-giants/erdjs-auth#1]
repro steps:

1. integrate maiar extension provider
UI:
2. click login button
3. select login with maiar extension
4. when the extension window appears, click outside the window

Expected: the extension popup to hide
Actual: error in console and the extension window does not appear anymore if you click maiar extension login button

![image](https://user-images.githubusercontent.com/26706013/177281593-4648c11d-6db5-4c28-869e-836c8c4cac5b.png)

**Comment by vlad-d** [comment]
@bogdanIuga Thank you for opening this issue. A fix will be included in the next version, which will come soon.
